language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
env:
  - DB=mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE socialnetwork;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:install
  - php artisan migrate:refresh
  - php artisan db:seed

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache